server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5430/demoDB
    username: usr
    password: pwd
  flyway:
    enabled: true
  web:
    resources:
      static-locations: classpath:/static

logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: TRACE